import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import "swiper/css";
import "swiper/css/grid";
import "swiper/css/pagination";
import "swiper/css/navigation";

import { Providers } from "./providers";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className=" min-h-screen">
          <Providers>
            <div className="w-full">
              <div className="px-4 sm:px-6 md:px-8 lg:px-16 relative">
                <Header />
                <div className="max-w-7xl mx-auto">{children}</div>
              </div>
              <Footer />
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
