import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import "swiper/css";
import "swiper/css/grid";
import "swiper/css/pagination";
import "swiper/css/navigation";

import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import CartModal from "@/components/CartModal";
import ClientInitializer from "@/components/ClientInitializer";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { authOptions } from "../../utils/authOptions";
import SignInModal from "@/components/shared/SignInModal";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${roboto.className} flex flex-col min-h-screen`}>
        <Providers session={session}>
          <ClientInitializer />
          <div className="flex-grow">
            <div className="px-4 sm:px-6 md:px-8 lg:px-16 relative">
              <Header />
              <div className="max-w-7xl mx-auto">{children}</div>
            </div>
          </div>
          <Footer className="flex-shrink-0" />
          <CartModal />
          <SignInModal />
        </Providers>
      </body>
    </html>
  );
}
